# Copyright (c) 2022 K8s Network Plumbing Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if .Values.manifests.thirdpartyCertificate }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhookconf.name }}
  namespace: kube-system
webhooks:
  - name: {{ .Values.webhookconf.webhook.name }}
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: kube-sytem
        path: "/mutate"
      caBundle: {{ .Values.webhookconf.webhook.caBundle }}
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: "NotIn"
          values:
            - "kube-system"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
{{- end }}
