{{- if .Values.ingressClass.enabled -}}
  {{- if (semverCompare "<2.3.0" (.Chart.AppVersion)) -}}
    {{- fail "ERROR: IngressClass cannot be used with Traefik < 2.3.0" -}}
  {{- end -}}
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
  {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
  {{- else }}
    {{- fail "\n\n ERROR: You must have at least networking.k8s.io/v1beta1 to use ingressClass" }}
  {{- end }}
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefaultClass | quote }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  name: {{ template "traefik.fullname" . }}
spec:
  controller: traefik.io/ingress-controller
{{- end -}}
