apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data01-pvc-registry
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi             
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data02-pvc-chartmuseum
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data03-pvc-jobservice
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi     
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data04-pvc-database
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi      
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data05-pvc-redis
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi     
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data06-pvc-trivy
  namespace: harbor
spec:
  resources:
    requests:
      storage: 5Gi    
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data07-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce      
  storageClassName: "default"
  resources:
    requests:
      storage: 5Gi
---
#Jobservice
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data01-registry
  labels:
    type: local
spec:
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: harbor       
    name: data01-pvc-registry
  hostPath:
    path: "<<Data_Path>>/data_harbor/data01-registry"

---
#Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data02-chartmuseum
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor       
    name: data02-pvc-chartmuseum      
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data02-chartmuseum"
---
#Chartmuseum
apiVersion: v1
kind: PersistentVolume
metadata:     
  name: data03-jobservice
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor      
    name: data03-pvc-jobservice      
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data03-jobservice"

---
#Trivy
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data04-database
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor       
    name: data04-pvc-database      
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data04-database"

---
#Registry
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data05-redis
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor       
    name: data05-pvc-redis       
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data05-redis"

---
#Redis
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data06-trivy
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor      
    name: data06-pvc-trivy      
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data06"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data07
  labels:
    type: local
spec:
  claimRef:
    namespace: harbor      
    name: data07-pvc      
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<<Data_Path>>/data_harbor/data07"

